site_name: BobaDocs

nav:
  - Home: index.md
  - Programming: 
    - Introduction: home.md
    - Yeet: about.md
  - Resources: resources.md

theme: 
  name: material
  palette: 
    primary: teal
    accent: cyan
  feature:
    tabs: false
  logo: img/logo.png
  favicon: img/logo.png

markdown_extensions: 
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: 
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - codehilite


plugins:
  - search
  - git-revision-date-localized

site_name: 'BobaDocs'
site_description: 'Boba Bots 253 Documentation'
site_author: 'Boba Bots 253'
site_url: 'https://bobadocs.readthedocs.io/en/latest/'

repo_name: "MillsRoboticsTeam253/bobadocs"
repo_url: "https://github.com/MillsRoboticsTeam253/bobadocs"

extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'instagram'
      link: 'https://www.instagram.com/bobabots253/?hl=en'
    - type: 'github'
      link: 'https://github.com/MillsRoboticsTeam253/bobadocs'
    