site_name: BobaDocs
site_description: Software Documentation for Boba Bots 253
site_author: Boba Bots 253 Software Team 
site_url: https://bobadocs.readthedocs.io/en/latest/

repo_name: "MillsRoboticsTeam253/bobadocs"
repo_url: "https://github.com/MillsRoboticsTeam253/bobadocs"

#copyright: 'Copyright &copy; 2020 Elegant Rose Royal Tea'


nav:
  - Home: index.md
  - Learn Java:
    - Quickstart: learn java/quickstart.md
    - Resources: learn java/resources.md
  - Programming:
    - Introduction: programming/introduction.md
    - Github: programming/gitstuff.md
  - Contributing:
    - Introduction: contributing/contributing.md
    - With Python: contributing/with-python.md
    - Up to Date: contributing/updating.md
    - Contributing Resources: contributing/contresources.md
  - Software Resources: software_resources.md

theme: 
  name: material
  palette: 
    primary: cyan
    accent: teal
  font:
    text: Roboto Condensed
  features:
    - instant
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  favicon: assets/bbalone_vectorized.svg

markdown_extensions: 
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: 
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - codehilite

plugins:
  - search
  - git-revision-date

extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/solid/globe
      link: 'https://www.bobabots253.org/'
    - icon: fontawesome/brands/instagram
      link: 'https://www.instagram.com/bobabots253/'
    - icon: fontawesome/brands/github
      link: 'https://github.com/MillsRoboticsTeam253/'
    