site_name: BobaDocs
site_description: Software Documentation for Boba Bots 253
site_author: Boba Bots 253 Software Team 
site_url: https://bobadocs.readthedocs.io/en/latest/

repo_name: "MillsRoboticsTeam253/bobadocs"
repo_url: "https://github.com/MillsRoboticsTeam253/bobadocs"


nav:
  - Home: index.md
  - FRC Competition Overview: frc-competition-overview.md
  - Programming:
    - Introduction: programming/learn-java.md
    - Intro to Git & Github: programming/version-control.md
    - Intro to Robot Code: programming/intro-to-robot-code.md
    - Git Flow: programming/git-flow.md
    - Collaboration: programming/collaboration.md
    - FAQ: programming/faq.md
    - Resources: programming/resources.md
  - Robot Troubleshooting:
    - Introduction: troubleshooting/problemsolving.md
    - Common Issues: troubleshooting/common-issues.md
  - Contributing:
    - Introduction: contributing/contributing.md
    - With Python: contributing/with-python.md
    - Up to Date: contributing/updating.md
    - Contributing Resources: contributing/contresources.md

extra_css:
  - stylesheets/extra.css

theme: 
  name: material
  highlightjs: true
  hljs_languages:
      - java
      - python
  palette: 
    primary: cyan
    accent: teal
  font:
    text: Inter
  features:
    - instant
  icon:
    repo: fontawesome/brands/github
  logo: assets/icons/logo.png
  favicon: assets/icons/bbalone_vectorized.svg

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - codehilite

plugins:
  - search
  - git-revision-date

extra:
  social:
    - icon: fontawesome/solid/globe
      link: 'https://www.bobabots253.org/'
    - icon: fontawesome/brands/instagram
      link: 'https://www.instagram.com/bobabots253/'
    - icon: fontawesome/brands/github
      link: 'https://github.com/MillsRoboticsTeam253/'
    