site_name: BobaDocs
site_description: Documentation for Boba Bots 253
site_author: Boba Bots 253 Software Team 

repo_name: "MillsRoboticsTeam253/bobadocs"
repo_url: "https://github.com/MillsRoboticsTeam253/bobadocs"
edit_uri: ""


nav:
  - Home: index.md
  - FRC Overview: frc-competition-overview.md
  - Programming:
    - Introduction: programming/learn-java.md
    - Intro to Git & Github: programming/version-control.md
    - Intro to Robot Code: programming/intro-to-robot-code.md
    - Git Flow: programming/git-flow.md
    - Collaboration: programming/collaboration.md
    - Resources: programming/resources.md
    - Robot Troubleshooting:
      - Introduction: programming/troubleshooting/problemsolving.md
      - Common Issues: programming/troubleshooting/common-issues.md
  - Electronics:
    - Skills: electronics/skills.md
    - Sensors: electronics/sensors.md
  - Construction: 
    - Skills: Construction/skills.md
    - Tools: Construction/tools.md  
  - Onshape:
    - Lessons:
      - 1. Intro to Onshape: onshape/intro.md
      - 2. Sketching: onshape/sketching.md
      - 3. Creating Basic Parts: onshape/basic-parts.md
      - 4. Creating Complex Parts: onshape/complex-parts.md
      - 5. Navigating Assemblies: onshape/navigating-assemblies.md
    - Misc:
      - Useful Shortcuts: onshape/useful-shortcuts.md
  - Robots:
    - 2020: robots/2020.md
  - Contributing:
    - Introduction: contributing/contributing.md
    - With Python: contributing/with-python.md
    - Up to Date: contributing/updating.md
    - Contributing Resources: contributing/contresources.md

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/iframe.css
  - assets/stylesheets/video-admonition.css

theme: 
  name: material
  palette: 
    primary: cyan
    accent: teal
  font:
    text: Inter
  features:
    # - navigation.instant
    # we often change docs and don't want it getting cached by browsers
    - navigation.sections
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  logo: assets/icons/logo.png
  favicon: assets/icons/bbalone_vectorized.svg

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - codehilite

plugins:
  - search:
      prebuild_index: true
  - git-revision-date

extra:
  social:
    - icon: fontawesome/solid/globe
      link: 'https://www.bobabots253.org/'
    - icon: fontawesome/brands/instagram
      link: 'https://www.instagram.com/bobabots253/'
    - icon: fontawesome/brands/github
      link: 'https://github.com/MillsRoboticsTeam253/'
    
